sudo: false

language: 
  - cpp
env:
  global:
    - CC=gcc-6
    - CXX=g++-6

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6

before_install:
  - pip install --user cpp-coveralls

script: 
  - cd Debug
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make
  - ./Vajolet_unitTest
  
after_success:
- coveralls --gcov-options '\-lp' --root .. -E ".*Debug.*" -E ".*test.*"
